# Runtime/DataCodec/SConstruct
# Copyright (c) 2010 Sunside Inc., All Rights Reserved
# Author: Joe Riedel
# See Radiance/LICENSE for licensing terms.

Import('x')

def zlib():
	dir = 'zlib123/'
	x.add(dir + 'adler32.cpp')
	x.add(dir + 'compress.cpp')
	x.add(dir + 'crc32.cpp')
	x.add(dir + 'deflate.cpp')
	x.add(dir + 'infback.cpp')
	x.add(dir + 'inffast.cpp')
	x.add(dir + 'inflate.cpp')
	x.add(dir + 'inftrees.cpp')
	x.add(dir + 'trees.cpp')
	x.add(dir + 'uncompr.cpp')
	x.add(dir + 'zutil.cpp')

zlib()
x.add('Lmp.cpp')
x.add('ZLib.cpp')
