# Runtime/Container/SConstruct
# Copyright (c) 2010 Sunside Inc., All Rights Reserved
# Author: Joe Riedel
# See Radiance/LICENSE for licensing terms.

Import('x')

x.add('MathAffineMatrix4X4ReflectMap.cpp')
x.add('MathAxisAngleReflectMap.cpp')
x.add('MathEulerReflectMap.cpp')
x.add('MathMatrix4X4ReflectMap.cpp')
x.add('MathMatrixGeneralReflectMap.cpp')
x.add('MathQuaternionReflectMap.cpp')
x.add('MathRigidMatrix4X4ReflectMap.cpp')
x.add('MathSolidMatrix4X4ReflectMap.cpp')
x.add('MathVectorReflectMap.cpp')