# Runtime/Interface/SConstruct
# Copyright (c) 2010 Sunside Inc., All Rights Reserved
# Author: Joe Riedel
# See Radiance/LICENSE for licensing terms.

Import('x')

#x.add('InterfaceReflectMap.cpp')
#x.add('ComponentManager.cpp')
#x.add('ComponentManagerReflectMap.cpp')