# Main/SConstruct
# Builds main library
# Copyright (c) 2010 Sunside Inc., All Rights Reserved
# Author: Joe Riedel
# See Radiance/LICENSE for licensing terms.

Import('radvars')
Import('variant_dir')
Import('radiance_engine')
(build, source) = radvars

if build.ios():
	source = source.Clone()
	
def getbuilder():
	if build.tools() and build.pc():
		x = build.qtBuilder('Main', build, source, '.', variant_dir, 'LIB')
		return x				
	x = build.libBuilder('Main', build, source, '.', variant_dir)
	return x
	
x = getbuilder()
build.backend.configLua(x.source) # we use lua

if build.pc():
	build.backend.addCgPaths(x.source)
	z = x.add('PCMain.cpp')

if build.osx(): #OSX always launches via SDL
	x.add('SDLMain.m')
	
if build.ios():
	if build.switches.ios_simulator():
		build.backend.addCCFlag(x.source, ['-fobjc-abi-version=2', '-fobjc-legacy-dispatch'])
	build.backend.addCCFlag(x.source, ['-fpascal-strings'])
	x.add('IOSMain.mm')
	
###############################################################################
# Export
###############################################################################
radiance_main = x.create()
Export('radiance_main')
