# Main/SConstruct
# Builds main library
# Copyright (c) 2010 Sunside Inc., All Rights Reserved
# Author: Joe Riedel
# See Radiance/LICENSE for licensing terms.

Import('radvars')
Import('variant_dir')
Import('radiance_engine')
(build, source) = radvars

def getbuilder():
	if build.tools() and build.pc():
		x = build.qtBuilder('Main', build, source, '.', variant_dir, 'LIB')
		return x				
	x = build.libBuilder('Main', build, source, '.', variant_dir)
	return x
	
x = getbuilder()
build.backend.configLua(x.source) # we use lua

if build.pc():
	build.backend.addCgPaths(x.source)
	z = x.add('PCMain.cpp')

if build.osx(): #OSX always launches via SDL
	x.add('SDLMain.mm')
	x.add('IOSMacLangPrefs.mm')
	
x.add('SystemLanguage.cpp')
	
###############################################################################
# Export
###############################################################################
radiance_main = x.create()
Export('radiance_main')
