# Runtime/Tools/QtTest/SConstruct
# Builds QtTest App
# Copyright (c) 2010 Sunside Inc., All Rights Reserved
# Author: Joe Riedel
# See Radiance/LICENSE for licensing terms.

Import('radvars')
Import('variant_dir')
(build, source) = radvars

x = build.qtBuilder('qtTest', build, source, '.', variant_dir)
x.uic.add('MainWindow.ui')
x.moc('MainWindow.cpp', 'MainWindow.h')
x.addQtSrc('Main.cpp')
x.create()
