# Runtime/Container/SConstruct
# Copyright (c) 2010 Sunside Inc., All Rights Reserved
# Author: Joe Riedel
# See Radiance/LICENSE for licensing terms.

Import('x')

x.add('LWNodeList.cpp')
x.add('LWRedBlackNodeTree.cpp')
x.add('NodeList.cpp')
x.add('RedBlackNodeTree.cpp')